---
title: "Toronto's Covid-19 Impact: How did Age and Gender affect Outcomes?"
author: 
  - Dhruv Gupta
thanks: "Code and data are available at: https://github.com/dhruv5423/Covid19-R-Project"
date: "today"
date-format: long
abstract: "The Covid-19 Pandemic caused irreparable damage to the infrastructure of our global systems, highlighting the neccessity to better understand factors that influence health outcomes. This paper uses data from OpenDataToronto to investigate how age and gender affects outcomes of those infected with the virus. xyz about results"
format: pdf
toc: true
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

#Loading Packages
library(tidyverse)
library(here)
library(palmerpenguins)
library(opendatatoronto)
library(tinytex)

#Loading Data
raw_covid_data <- read.csv(here("data/raw_data/raw_covid_data.csv"))
cleaned_covid_data <- read.csv(here("data/analysis_data/cleaned_covid_data.csv"))
```

# Introduction

The Covid-19 Pandemic has had an unimaginable effect on human lives around the globe. As of April 13, 2024, Worldometer Info estimates that over 704 million people worldwide have contracted the virus, resulting in approximately 7 million deaths [@worldometer]. In Canada alone, there have been almost 4.6 million reported cases and more than 38,000 deaths as of July 20, 2024 [@infobase_ca].

While these statistics paint a harrowing picture of the human toll inflicted, the pandemic has exacerbated existing economic inequalities, destabilized political systems, and put immense pressure on societal infrastructure globally. Looking past the immediate health crisis, lockdowns and restrictions have had immeasurable impacts not only on global supply chains, but also on the mental heatlh of many forced to quarantine or self isolate.

An article by Fortune valued the economic burden on the US Economy to be upwards of \$14 Trillion USD at the end of 2023 [@fortune]. While this figure mainly took into account the 'standard economic effects' of the pandemic - revenue lost due to mandatory business closures, decreases in air travel, and workplace absences - the article noted that there were many unobservable factors that were incredibly burdernsome to the economy, such as long term physical and mental health effects of the pandemic on the population.

Covid-19 has been found to have varying effects across demographics. A 2020 article published in the PLOS Journal found that 'Covid-19 may be associated with worse outcomes in males than in females'. The article found that men are up to 22% more likely to require ICU admission.

Moreover, an article published in the Springer Link Journal in 2021 found that older adults, in particular those above the age of 65, face higher mortality rates than their younger counterparts. Weaker immune systems, and the higher likely presence of other conditions can exacerbate the effects of the virus.

Understanding how demographic variables like age and gender affect outcomes related to contracting viruses is increasingly important in the shaping of future policies and health measures. This paper aims to analyse the differences in outcomes for various age groups and genders among Covid-19 cases in Toronto, in an effort to contribute to deepening our understanding of the risk factors that may impact the lives of those with Covid-19, and possibly in future pandemics as well.

The remainder of this paper is structured as follows. @sec-data xyz @sec-results xyz @sec-discussion xyz.

# Data {#sec-data}

We use @citeR and @rohan.

## Data Selection and Measurement

## Raw Data

## Data Cleaning

Talk way more about it.

## Summary Statistics

# Results {#sec-results}

## Cases over Time

## Age vs Outcomes

## Gender vs Outcomes

# Discussion {#sec-discussion}

## Effect of Age on Outcomes

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this.

## Effect of Gender on Outcomes

## Broader Discussion and Takeaways

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

# References

# LLM Disclosure
